#COMAKE2 edit-mode: -*- Makefile -*-
####################64Bit Mode####################
ifeq ($(shell uname -m),x86_64)
CC=gcc
CXX=g++
CXXFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CFLAGS=-g \
  -pipe \
  -W \
  -Wall \
  -fPIC
CPPFLAGS=-D_GNU_SOURCE \
  -D__STDC_LIMIT_MACROS \
  -DVERSION=\"1.9.8.7\"
INCPATH=-I. \
  -I./include \
  -I./output \
  -I./output/include
DEP_INCPATH=-I../../../../../com/idlcompiler \
  -I../../../../../com/idlcompiler/include \
  -I../../../../../com/idlcompiler/output \
  -I../../../../../com/idlcompiler/output/include \
  -I../../../../../lib2-64/bsl \
  -I../../../../../lib2-64/bsl/include \
  -I../../../../../lib2-64/bsl/output \
  -I../../../../../lib2-64/bsl/output/include \
  -I../../../../../lib2-64/ccode \
  -I../../../../../lib2-64/ccode/include \
  -I../../../../../lib2-64/ccode/output \
  -I../../../../../lib2-64/ccode/output/include \
  -I../../../../../lib2-64/dict \
  -I../../../../../lib2-64/dict/include \
  -I../../../../../lib2-64/dict/output \
  -I../../../../../lib2-64/dict/output/include \
  -I../../../../../lib2-64/htmlparser2 \
  -I../../../../../lib2-64/htmlparser2/include \
  -I../../../../../lib2-64/htmlparser2/output \
  -I../../../../../lib2-64/htmlparser2/output/include \
  -I../../../../../lib2-64/libcrf \
  -I../../../../../lib2-64/libcrf/include \
  -I../../../../../lib2-64/libcrf/output \
  -I../../../../../lib2-64/libcrf/output/include \
  -I../../../../../lib2-64/others-ex \
  -I../../../../../lib2-64/others-ex/include \
  -I../../../../../lib2-64/others-ex/output \
  -I../../../../../lib2-64/others-ex/output/include \
  -I../../../../../lib2-64/ullib \
  -I../../../../../lib2-64/ullib/include \
  -I../../../../../lib2-64/ullib/output \
  -I../../../../../lib2-64/ullib/output/include \
  -I../../../../../lib2-64/wordrank \
  -I../../../../../lib2-64/wordrank/include \
  -I../../../../../lib2-64/wordrank/output \
  -I../../../../../lib2-64/wordrank/output/include \
  -I../../../../../lib2-64/wordseg \
  -I../../../../../lib2-64/wordseg/include \
  -I../../../../../lib2-64/wordseg/output \
  -I../../../../../lib2-64/wordseg/output/include \
  -I../../../../../public/bslext \
  -I../../../../../public/bslext/include \
  -I../../../../../public/bslext/output \
  -I../../../../../public/bslext/output/include \
  -I../../../../../public/comlog-plugin \
  -I../../../../../public/comlog-plugin/include \
  -I../../../../../public/comlog-plugin/output \
  -I../../../../../public/comlog-plugin/output/include \
  -I../../../../../public/configure \
  -I../../../../../public/configure/include \
  -I../../../../../public/configure/output \
  -I../../../../../public/configure/output/include \
  -I../../../../../public/connectpool \
  -I../../../../../public/connectpool/include \
  -I../../../../../public/connectpool/output \
  -I../../../../../public/connectpool/output/include \
  -I../../../../../public/gm/galileo \
  -I../../../../../public/gm/galileo/include \
  -I../../../../../public/gm/galileo/output \
  -I../../../../../public/gm/galileo/output/include \
  -I../../../../../public/idlcompiler \
  -I../../../../../public/idlcompiler/include \
  -I../../../../../public/idlcompiler/output \
  -I../../../../../public/idlcompiler/output/include \
  -I../../../../../public/mcpack \
  -I../../../../../public/mcpack/include \
  -I../../../../../public/mcpack/output \
  -I../../../../../public/mcpack/output/include \
  -I../../../../../public/nshead \
  -I../../../../../public/nshead/include \
  -I../../../../../public/nshead/output \
  -I../../../../../public/nshead/output/include \
  -I../../../../../public/odict \
  -I../../../../../public/odict/include \
  -I../../../../../public/odict/output \
  -I../../../../../public/odict/output/include \
  -I../../../../../public/spreg \
  -I../../../../../public/spreg/include \
  -I../../../../../public/spreg/output \
  -I../../../../../public/spreg/output/include \
  -I../../../../../public/ub \
  -I../../../../../public/ub/include \
  -I../../../../../public/ub/output \
  -I../../../../../public/ub/output/include \
  -I../../../../../public/uconv \
  -I../../../../../public/uconv/include \
  -I../../../../../public/uconv/output \
  -I../../../../../public/uconv/output/include \
  -I../../../../../third-64/boost \
  -I../../../../../third-64/boost/include \
  -I../../../../../third-64/boost/output \
  -I../../../../../third-64/boost/output/include \
  -I../../../../../third-64/pcre \
  -I../../../../../third-64/pcre/include \
  -I../../../../../third-64/pcre/output \
  -I../../../../../third-64/pcre/output/include \
  -I../../../../../third-64/stlport \
  -I../../../../../third-64/stlport/include \
  -I../../../../../third-64/stlport/output \
  -I../../../../../third-64/stlport/output/include \
  -I../../../../../thirdsrc/zookeeper \
  -I../../../../../thirdsrc/zookeeper/include \
  -I../../../../../thirdsrc/zookeeper/output \
  -I../../../../../thirdsrc/zookeeper/output/include

#============ CCP vars ============
CCHECK=@ccheck.py
CCHECK_FLAGS=
PCLINT=@pclint
PCLINT_FLAGS=
CCP=@ccp.py
CCP_FLAGS=


#COMAKE UUID
COMAKE_MD5=a3f097008dfd4bb15b91e735251f0f44  COMAKE


.PHONY:all
all:comake2_makefile_check simhash 
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mall[0m']"
	@echo "make all done"

.PHONY:comake2_makefile_check
comake2_makefile_check:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mcomake2_makefile_check[0m']"
	#in case of error, update 'Makefile' by 'comake2'
	@echo "$(COMAKE_MD5)">comake2.md5
	@md5sum -c --status comake2.md5
	@rm -f comake2.md5

.PHONY:ccpclean
ccpclean:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mccpclean[0m']"
	@echo "make ccpclean done"

.PHONY:clean
clean:ccpclean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mclean[0m']"
	rm -rf simhash
	rm -rf ./output/bin/simhash
	rm -rf simhash_ks.o
	rm -rf simhash_client.o
	rm -rf simhash_termrate.o
	rm -rf simhash_main.o
	rm -rf simhash_msgpack.o
	rm -rf simhash_sim_process.o
	rm -rf simhash_sim_conf.o
	rm -rf simhash_normalize.o
	rm -rf simhash_utils.o
	rm -rf simhash_segmentor.o
	rm -rf simhash_hashsign.o
	rm -rf simhash_redis.o

.PHONY:dist
dist:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdist[0m']"
	tar czvf output.tar.gz output
	@echo "make dist done"

.PHONY:distclean
distclean:clean
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mdistclean[0m']"
	rm -f output.tar.gz
	@echo "make distclean done"

.PHONY:love
love:
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40mlove[0m']"
	@echo "make love done"

simhash:simhash_ks.o \
  simhash_client.o \
  simhash_termrate.o \
  simhash_main.o \
  simhash_msgpack.o \
  simhash_sim_process.o \
  simhash_sim_conf.o \
  simhash_normalize.o \
  simhash_utils.o \
  simhash_segmentor.o \
  simhash_hashsign.o \
  simhash_redis.o
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash[0m']"
	$(CXX) simhash_ks.o \
  simhash_client.o \
  simhash_termrate.o \
  simhash_main.o \
  simhash_msgpack.o \
  simhash_sim_process.o \
  simhash_sim_conf.o \
  simhash_normalize.o \
  simhash_utils.o \
  simhash_segmentor.o \
  simhash_hashsign.o \
  simhash_redis.o -Xlinker "-("  ../../../../../com/idlcompiler/astyle/libastyle.a \
  ../../../../../com/idlcompiler/cxx/libskeleton.a \
  ../../../../../com/idlcompiler/parser/libparser.a \
  ../../../../../lib2-64/bsl/lib/libbsl.a \
  ../../../../../lib2-64/bsl/lib/libbsl_ResourcePool.a \
  ../../../../../lib2-64/bsl/lib/libbsl_archive.a \
  ../../../../../lib2-64/bsl/lib/libbsl_buffer.a \
  ../../../../../lib2-64/bsl/lib/libbsl_check_cast.a \
  ../../../../../lib2-64/bsl/lib/libbsl_exception.a \
  ../../../../../lib2-64/bsl/lib/libbsl_pool.a \
  ../../../../../lib2-64/bsl/lib/libbsl_utils.a \
  ../../../../../lib2-64/bsl/lib/libbsl_var.a \
  ../../../../../lib2-64/bsl/lib/libbsl_var_implement.a \
  ../../../../../lib2-64/bsl/lib/libbsl_var_utils.a \
  ../../../../../lib2-64/ccode/lib/libulccode.a \
  ../../../../../lib2-64/dict/lib/libuldict.a \
  ../../../../../lib2-64/htmlparser2/lib/libhtmlparser2.a \
  ../../../../../lib2-64/libcrf/lib/libcrf.a \
  ../../../../../lib2-64/others-ex/lib/libullib_ex.a \
  ../../../../../lib2-64/ullib/lib/libullib.a \
  ../../../../../lib2-64/wordrank/lib/libwordrank.a \
  ../../../../../lib2-64/wordseg/libsegment.a \
  ../../../../../public/bslext/output/lib/libbsl_bml.a \
  ../../../../../public/bslext/output/lib/libbsl_containers_utils.a \
  ../../../../../public/bslext/output/lib/libbsl_var_scripting.a \
  ../../../../../public/bslext/output/lib/libbsl_var_serializer.a \
  ../../../../../public/bslext/output/lib/libbsl_var_vscript.a \
  ../../../../../public/bslext/output/lib/libbsl_vs.a \
  ../../../../../public/bslext/output/lib/libbslext.a \
  ../../../../../public/comlog-plugin/libcomlog.a \
  ../../../../../public/comlog-plugin/output/lib/libdfsappender.a \
  ../../../../../public/configure/libconfig.a \
  ../../../../../public/connectpool/libconnectpool.a \
  ../../../../../public/gm/galileo/libgalileo.a \
  ../../../../../public/gm/galileo/output/lib/libzookeeper_mt.a \
  ../../../../../public/idlcompiler/output/lib/libmcpack_idl.a \
  ../../../../../public/mcpack/libmcpack.a \
  ../../../../../public/nshead/libnshead.a \
  ../../../../../public/odict/libodict.a \
  ../../../../../public/spreg/libspreg.a \
  ../../../../../public/ub/output/lib/libub.a \
  ../../../../../public/ub/output/lib/libub_aserver.a \
  ../../../../../public/ub/output/lib/libub_client.a \
  ../../../../../public/ub/output/lib/libub_conf.a \
  ../../../../../public/ub/output/lib/libub_galileo.a \
  ../../../../../public/ub/output/lib/libub_log.a \
  ../../../../../public/ub/output/lib/libub_misc.a \
  ../../../../../public/ub/output/lib/libub_monitor.a \
  ../../../../../public/ub/output/lib/libub_server.a \
  ../../../../../public/ub/output/lib/libubex.a \
  ../../../../../public/ub/output/lib/libubfw.a \
  ../../../../../public/uconv/libuconv.a \
  ../../../../../third-64/pcre/lib/libpcre.a \
  ../../../../../third-64/pcre/lib/libpcrecpp.a \
  ../../../../../third-64/pcre/lib/libpcreposix.a \
  ../../../../../thirdsrc/zookeeper/output/lib/libzookeeper_mt.a \
  ../../../../../thirdsrc/zookeeper/output/lib/libzookeeper_st.a -lpthread \
  -lcrypto \
  -lrt -Xlinker "-)" -o simhash
	mkdir -p ./output/bin
	cp -f --link simhash ./output/bin

simhash_ks.o:ks.cpp \
  normalize.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_ks.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_ks.o ks.cpp

simhash_client.o:client.cpp \
  client.h \
  sim_include.h \
  sim_conf.h \
  sim_struct.h \
  comdef.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_client.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_client.o client.cpp

simhash_termrate.o:termrate.cpp \
  termrate.h \
  sim_include.h \
  sim_struct.h \
  comdef.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_termrate.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_termrate.o termrate.cpp

simhash_main.o:main.cpp \
  sim_include.h \
  sim_process.h \
  sim_conf.h \
  sim_struct.h \
  comdef.h \
  segmentor.h \
  client.h \
  normalize.h \
  termrate.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_main.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_main.o main.cpp

simhash_msgpack.o:msgpack.cpp \
  msgpack.h \
  sim_struct.h \
  sim_include.h \
  comdef.h \
  redis.h \
  sim_conf.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_msgpack.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_msgpack.o msgpack.cpp

simhash_sim_process.o:sim_process.cpp \
  sim_process.h \
  sim_include.h \
  sim_struct.h \
  comdef.h \
  msgpack.h \
  redis.h \
  segmentor.h \
  hashsign.h \
  sim_conf.h \
  normalize.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_sim_process.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_sim_process.o sim_process.cpp

simhash_sim_conf.o:sim_conf.cpp \
  sim_conf.h \
  sim_struct.h \
  sim_include.h \
  comdef.h \
  utils.h \
  client.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_sim_conf.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_sim_conf.o sim_conf.cpp

simhash_normalize.o:normalize.cpp \
  normalize.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_normalize.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_normalize.o normalize.cpp

simhash_utils.o:utils.cpp \
  sim_include.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_utils.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_utils.o utils.cpp

simhash_segmentor.o:segmentor.cpp \
  segmentor.h \
  sim_struct.h \
  sim_include.h \
  comdef.h \
  utils.h \
  sim_conf.h \
  termrate.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_segmentor.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_segmentor.o segmentor.cpp

simhash_hashsign.o:hashsign.cpp \
  hashsign.h \
  sim_struct.h \
  sim_include.h \
  comdef.h \
  redis.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_hashsign.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_hashsign.o hashsign.cpp

simhash_redis.o:redis.cpp \
  redis.h \
  sim_include.h \
  comdef.h \
  sim_struct.h \
  client.h \
  msgpack.h \
  sim_conf.h
	@echo "[[1;32;40mCOMAKE:BUILD[0m][Target:'[1;32;40msimhash_redis.o[0m']"
	$(CXX) -c $(INCPATH) $(DEP_INCPATH) $(CPPFLAGS) $(CXXFLAGS)  -o simhash_redis.o redis.cpp

endif #ifeq ($(shell uname -m),x86_64)


